---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: got-relationships-deployment
  labels:
    app: got-relationships
    razee/watch-resource: detail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: got-relationships
  template:
    metadata:
      labels:
        app: got-relationships
    spec:
      containers:
      - name: app
        image: us.icr.io/jtpape/got-relationships:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: got-relationships-service
  labels:
    razee/watch-resource: detail
spec:
  selector:
    app: got-relationships
  ports:
  - protocol: TCP
    port: 8081 
    name: http
    targetPort: 8081
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: got-relationships-ingress  
  labels:
    razee/watch-resource: detail  
spec:
  rules:
  - host: got-relationships.apps.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: got-relationships-service
          servicePort: 8081
