name: CI

on:
  push:
  - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/docker/cli@master
    - name: Build the image
      run: docker build -t jpapejr/got-relationships:latest
    - name: Push the image
      run: docker push jpapejr/got-relationships:latest
